name: X-NUCLEO-IKS01A1 Continuous Integration
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*'
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '*'
      - '**.md'
      - '**.txt'
jobs:
  # Astyle not needed here as only one include file
  # astyle_check:
  #   runs-on: ubuntu-latest
  #   name: AStyle check
  #   steps:
  #   # First of all, clone the repo using the checkout action.
  #   - name: Checkout
  #     uses: actions/checkout@master

  #   - name: Astyle check
  #     id: Astyle
  #     uses: fpistm/actions/astyle-check@master

  #   # Use the output from the `Astyle` step
  #   - name: Astyle Errors
  #     if: failure()
  #     run: |
  #       cat ${{ steps.Astyle.outputs.astyle-result }}
  #       exit 1
  spell-check:
    runs-on: ubuntu-latest
    name: Spell check
    steps:
    - uses: actions/checkout@master
    - uses: arduino/actions/libraries/spell-check@master
      with:
        ignore-words-list: "./extras/codespell-ignore-words-list.txt"
  lib_build:
    runs-on: ubuntu-latest
    name: Library compilation
    steps:
    # First of all, clone the repo using the checkout action.
    - name: Checkout
      uses: actions/checkout@master

    - name: Compilation
      id: Compile
      uses: stm32duino/actions/compile-examples@master
      with:
        board-pattern: "NUCLEO_L476RG"
        libraries: "STM32duino LSM6DS0, STM32duino LSM6DS3, STM32duino LIS3MDL, STM32duino HTS221, STM32duino LPS25HB"

    # Use the output from the `Compile` step
    - name: Compilation Errors
      if: failure()
      run: |
        cat ${{ steps.Compile.outputs.compile-result }}
        exit 1